# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.CreateFileVersionRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :signatureMd5,
    :signatureSizeInBytes,
    :fileMd5,
    :fileSizeInBytes
  ]

  @type t :: %__MODULE__{
    :signatureMd5 => String.t,
    :signatureSizeInBytes => float(),
    :fileMd5 => String.t | nil,
    :fileSizeInBytes => float() | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.CreateFileVersionRequest do
  def decode(value, _options) do
    value
  end
end

