# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.FileUploadUrl do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :url
  ]

  @type t :: %__MODULE__{
    :url => String.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.FileUploadUrl do
  def decode(value, _options) do
    value
  end
end

