# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.InfoPushDataArticleContent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :text,
    :imageUrl,
    :onPressed
  ]

  @type t :: %__MODULE__{
    :text => String.t | nil,
    :imageUrl => String.t | nil,
    :onPressed => VRChat.Model.InfoPushDataClickable.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.InfoPushDataArticleContent do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:onPressed, :struct, VRChat.Model.InfoPushDataClickable, options)
  end
end

