# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.InfoPushData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :contentList,
    :description,
    :imageUrl,
    :name,
    :onPressed,
    :template,
    :version,
    :article
  ]

  @type t :: %__MODULE__{
    :contentList => VRChat.Model.DynamicContentRow.t | nil,
    :description => String.t | nil,
    :imageUrl => String.t | nil,
    :name => String.t | nil,
    :onPressed => VRChat.Model.InfoPushDataClickable.t | nil,
    :template => String.t | nil,
    :version => String.t | nil,
    :article => VRChat.Model.InfoPushDataArticle.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.InfoPushData do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:contentList, :struct, VRChat.Model.DynamicContentRow, options)
    |> deserialize(:onPressed, :struct, VRChat.Model.InfoPushDataClickable, options)
    |> deserialize(:article, :struct, VRChat.Model.InfoPushDataArticle, options)
  end
end

