# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.InstanceShortNameResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :secureName,
    :shortName
  ]

  @type t :: %__MODULE__{
    :secureName => String.t,
    :shortName => String.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.InstanceShortNameResponse do
  def decode(value, _options) do
    value
  end
end

