# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.LimitedUnityPackage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :platform,
    :unityVersion
  ]

  @type t :: %__MODULE__{
    :platform => String.t,
    :unityVersion => String.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.LimitedUnityPackage do
  def decode(value, _options) do
    value
  end
end

