# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.Permission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :ownerId,
    :data
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :ownerId => String.t,
    :data => map() | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.Permission do
  def decode(value, _options) do
    value
  end
end

