# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.PublicAnnouncement do
  @moduledoc """
  Public Announcement
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :text
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :text => String.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.PublicAnnouncement do
  def decode(value, _options) do
    value
  end
end

