# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.UpdateUserRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :birthday,
    :acceptedTOSVersion,
    :tags,
    :status,
    :statusDescription,
    :bio,
    :bioLinks,
    :userIcon
  ]

  @type t :: %__MODULE__{
    :email => String.t | nil,
    :birthday => Date.t | nil,
    :acceptedTOSVersion => float() | nil,
    :tags => [VRChat.Model.String.t] | nil,
    :status => VRChat.Model.UserStatus.t | nil,
    :statusDescription => String.t | nil,
    :bio => String.t | nil,
    :bioLinks => [String.t] | nil,
    :userIcon => String.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.UpdateUserRequest do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:birthday, :date, nil, options)
    |> deserialize(:status, :struct, VRChat.Model.UserStatus, options)
  end
end

