# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.WorldMetadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :metadata => map()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.WorldMetadata do
  def decode(value, _options) do
    value
  end
end

