# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.ApiEventConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :distanceClose,
    :distanceFactor,
    :distanceFar,
    :groupDistance,
    :maximumBunchSize,
    :notVisibleFactor,
    :playerOrderBucketSize,
    :playerOrderFactor,
    :slowUpdateFactorThreshold,
    :viewSegmentLength
  ]

  @type t :: %__MODULE__{
    :distanceClose => integer(),
    :distanceFactor => integer(),
    :distanceFar => integer(),
    :groupDistance => integer(),
    :maximumBunchSize => integer(),
    :notVisibleFactor => integer(),
    :playerOrderBucketSize => integer(),
    :playerOrderFactor => integer(),
    :slowUpdateFactorThreshold => integer(),
    :viewSegmentLength => integer()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.ApiEventConfig do
  def decode(value, _options) do
    value
  end
end

