# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.Avatar do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :assetUrl,
    :assetUrlObject,
    :authorId,
    :authorName,
    :created_at,
    :description,
    :featured,
    :id,
    :imageUrl,
    :name,
    :releaseStatus,
    :tags,
    :thumbnailImageUrl,
    :unityPackageUrl,
    :unityPackageUrlObject,
    :unityPackages,
    :updated_at,
    :version
  ]

  @type t :: %__MODULE__{
    :assetUrl => String.t | nil,
    :assetUrlObject => map() | nil,
    :authorId => String.t,
    :authorName => String.t,
    :created_at => DateTime.t,
    :description => String.t,
    :featured => boolean(),
    :id => String.t,
    :imageUrl => String.t,
    :name => String.t,
    :releaseStatus => VRChat.Model.ReleaseStatus.t,
    :tags => [VRChat.Model.String.t],
    :thumbnailImageUrl => String.t,
    :unityPackageUrl => String.t,
    :unityPackageUrlObject => VRChat.Model.AvatarUnityPackageUrlObject.t,
    :unityPackages => [VRChat.Model.UnityPackage.t],
    :updated_at => DateTime.t,
    :version => integer()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.Avatar do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:releaseStatus, :struct, VRChat.Model.ReleaseStatus, options)
    |> deserialize(:unityPackageUrlObject, :struct, VRChat.Model.AvatarUnityPackageUrlObject, options)
    |> deserialize(:unityPackages, :list, VRChat.Model.UnityPackage, options)
  end
end

