# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.CreateAvatarRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :assetUrl,
    :id,
    :name,
    :description,
    :tags,
    :imageUrl,
    :releaseStatus,
    :version,
    :unityPackageUrl
  ]

  @type t :: %__MODULE__{
    :assetUrl => String.t | nil,
    :id => String.t | nil,
    :name => String.t,
    :description => String.t | nil,
    :tags => [VRChat.Model.String.t] | nil,
    :imageUrl => String.t,
    :releaseStatus => VRChat.Model.ReleaseStatus.t | nil,
    :version => float() | nil,
    :unityPackageUrl => String.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.CreateAvatarRequest do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:releaseStatus, :struct, VRChat.Model.ReleaseStatus, options)
  end
end

