# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.DynamicContentRow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :index,
    :name,
    :platform,
    :sortHeading,
    :sortOrder,
    :sortOwnership,
    :tag,
    :type
  ]

  @type t :: %__MODULE__{
    :index => integer() | nil,
    :name => String.t,
    :platform => String.t,
    :sortHeading => String.t,
    :sortOrder => String.t,
    :sortOwnership => String.t,
    :tag => String.t | nil,
    :type => String.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.DynamicContentRow do
  def decode(value, _options) do
    value
  end
end

