# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.Error do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => VRChat.Model.Response.t | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.Error do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:error, :struct, VRChat.Model.Response, options)
  end
end

