# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.FinishFileDataUploadRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :etags,
    :nextPartNumber,
    :maxParts
  ]

  @type t :: %__MODULE__{
    :etags => [String.t] | nil,
    :nextPartNumber => String.t,
    :maxParts => String.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.FinishFileDataUploadRequest do
  def decode(value, _options) do
    value
  end
end

