# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.InfoPushDataClickable do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :command,
    :parameters
  ]

  @type t :: %__MODULE__{
    :command => String.t,
    :parameters => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: VRChat.Model.InfoPushDataClickable do
  def decode(value, _options) do
    value
  end
end

