# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.InviteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :responseSlot
  ]

  @type t :: %__MODULE__{
    :responseSlot => integer()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.InviteResponse do
  def decode(value, _options) do
    value
  end
end

