# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.PastDisplayName do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :displayName,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :displayName => String.t,
    :updated_at => DateTime.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.PastDisplayName do
  def decode(value, _options) do
    value
  end
end

