# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.PlayerModeration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :created,
    :id,
    :sourceDisplayName,
    :sourceUserId,
    :targetDisplayName,
    :targetUserId,
    :type
  ]

  @type t :: %__MODULE__{
    :created => DateTime.t,
    :id => String.t,
    :sourceDisplayName => String.t,
    :sourceUserId => String.t,
    :targetDisplayName => String.t,
    :targetUserId => String.t,
    :type => VRChat.Model.PlayerModerationType.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.PlayerModeration do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VRChat.Model.PlayerModerationType, options)
  end
end

