# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.TransactionAgreement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :agreementId,
    :itemId,
    :status,
    :period,
    :frequency,
    :billingType,
    :startDate,
    :endDate,
    :recurringAmt,
    :currency,
    :timeCreated,
    :nextPayment,
    :lastPayment,
    :lastAmount,
    :lastAmountVat,
    :outstanding,
    :failedAttempts
  ]

  @type t :: %__MODULE__{
    :agreementId => String.t,
    :itemId => float(),
    :status => String.t,
    :period => String.t,
    :frequency => float(),
    :billingType => String.t,
    :startDate => String.t,
    :endDate => String.t,
    :recurringAmt => float(),
    :currency => String.t,
    :timeCreated => String.t,
    :nextPayment => String.t,
    :lastPayment => String.t,
    :lastAmount => float(),
    :lastAmountVat => float(),
    :outstanding => float(),
    :failedAttempts => float()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.TransactionAgreement do
  def decode(value, _options) do
    value
  end
end

