# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.TransactionSteamWalletInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :state,
    :country,
    :currency,
    :status
  ]

  @type t :: %__MODULE__{
    :state => String.t,
    :country => String.t,
    :currency => String.t,
    :status => String.t
  }
end

defimpl Poison.Decoder, for: VRChat.Model.TransactionSteamWalletInfo do
  def decode(value, _options) do
    value
  end
end

