# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule VRChat.Model.UserSubscription do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :transactionId,
    :store,
    :steamItemId,
    :amount,
    :description,
    :period,
    :tier,
    :active,
    :status,
    :expires,
    :created_at,
    :updated_at,
    :licenseGroups,
    :isGift
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :transactionId => String.t,
    :store => String.t,
    :steamItemId => String.t | nil,
    :amount => float(),
    :description => String.t,
    :period => VRChat.Model.SubscriptionPeriod.t,
    :tier => float(),
    :active => boolean(),
    :status => VRChat.Model.TransactionStatus.t,
    :expires => DateTime.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :licenseGroups => [VRChat.Model.String.t],
    :isGift => boolean()
  }
end

defimpl Poison.Decoder, for: VRChat.Model.UserSubscription do
  import VRChat.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:period, :struct, VRChat.Model.SubscriptionPeriod, options)
    |> deserialize(:status, :struct, VRChat.Model.TransactionStatus, options)
  end
end

